# Generated by Django 6.0.1 on 2026-01-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='level',
            field=models.CharField(choices=[('baby', '0-1'), ('kid', '2-4'), ('adult', '5+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='reps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rest',
            field=models.IntegerField(help_text='Rest in seconds'),
        ),
    ]
