# Generated by Django 6.0.1 on 2026-01-30 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_exercise_kind_exercise_slug_alter_exercise_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='training_age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='training_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='WorkoutSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_bracket', models.CharField(max_length=10)),
                ('phase', models.IntegerField()),
                ('slot_number', models.IntegerField()),
                ('movement_pattern', models.CharField(max_length=100)),
                ('base_exercise', models.TextField()),
                ('too_easy_progression', models.TextField(blank=True, null=True)),
                ('too_hard_regression', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('training_bracket', 'phase', 'slot_number')},
            },
        ),
    ]
