# Generated by Django 6.0.1 on 2026-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_remove_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='training_age',
            field=models.IntegerField(default=1),
        ),
    ]
