# Generated by Django 6.0.1 on 2026-01-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_userprofile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSlotLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_bracket', models.CharField(max_length=10)),
                ('phase', models.IntegerField()),
                ('slot_number', models.IntegerField()),
                ('movement_pattern', models.CharField(max_length=100)),
                ('base_exercise', models.TextField()),
                ('progression_exercise', models.TextField(blank=True, null=True)),
                ('regression_exercise', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('training_bracket', 'phase', 'slot_number')},
            },
        ),
        migrations.DeleteModel(
            name='WorkoutSlot',
        ),
    ]
